name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: .
        branch: gh-pages

  deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST https://api.render.com/v1/services \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "name": "profile-backend",
            "owner": "hitheshmr",
            "type": "web_service",
            "branch": "main",
            "rootDir": "server",
            "buildCommand": "pip install -r requirements.txt",
            "startCommand": "gunicorn main:app",
            "envVars": [
              {
                "key": "FLASK_ENV",
                "value": "production"
              },
              {
                "key": "PORT",
                "value": "10000"
              }
            ],
            "plan": "free"
          }'